### ISSUE TITLE
You must have package.json/bower.json

### ISSUE THREAD

**Issue by agauniyal** [ganemone/NodeRequirer#87]
what if I just want to include node core modules :/ eg `http` or `fs`. I don't create a package.json everytime. If there is no package.json, atleast provide those core modules.

**Comment by agauniyal** [comment]
ping?

**Comment by megawac** [comment]
The main issue with this @agauniyal  is deciding where to stop establishing relative paths. NodeRequirer keeps walking up parent directories until a bower.json or package.json is found in order to establish the base path. All non ignored `js` files relative to this base path are included in the search. If there wasnt a base path the plugin would end up walking most of your file system! I don't know if its worth it to change the logic to not include relative paths if bower/package not found.

Personally, doing a quick npm init/ writing the core imports is not a big deal
